name = "WeightedMovingQuantileTrees"
uuid = "6ffb4879-b1bd-4751-a0be-d9af1615a109"
authors = ["Kevin Atteson <kevin@atteson.com>"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Statistics = "1.11.1"
